### ISSUE TITLE
Not receiving any data from Max! basic

### ISSUE THREAD

**Issue by haniham** [ioBroker/ioBroker.maxcul#12]
This night i built my own nanocul and i have mounted a thermostat to my heater.
After fixing some bugs i managed to set up the cul and pair the thermostat.

Already in iobroker a new object was created and via writing to the desiitredTemperature the thermostat value is being adjusted, so the communication is working fine.

But i am not recieving any values from the thermostat

![grafik](https://user-images.githubusercontent.com/4102949/46904539-e33c1b80-cee5-11e8-8dbe-bfba4d162e77.png)

**Comment by Apollon77** [comment]
Please post debug log.

**Comment by haniham** [comment]
sorry to let you wait so long:
this evening i started my computer
somewhere after i manually restarted the adapter at 21:02 up until now it has set back  the thermometers desired Temperature to 17°C which was already standing in the objects before.

and it received some actual data:
![grafik](https://user-images.githubusercontent.com/4102949/47048787-ad27c180-d19b-11e8-9b99-cf9488a7148d.png)

Todays log:
![grafik](https://user-images.githubusercontent.com/4102949/47048938-22939200-d19c-11e8-8540-23ac426e9424.png)
maxcul.0 | 2018-10-16 23:03:06.615 | info | Packet 0f0104031234561234560012101782b6 sent but no response!
-- | -- | -- | --
maxcul.0 | 2018-10-16 23:02:54.613 | info | checkTimeIntervalFired
maxcul.0 | 2018-10-16 22:03:06.616 | info | Packet 0f0104031234561234560012101682b6 sent but no response!
maxcul.0 | 2018-10-16 22:02:54.603 | info | checkTimeIntervalFired
maxcul.0 | 2018-10-16 21:02:56.707 | info | CUL FW Version: V 1.67 nanoCUL868
maxcul.0 | 2018-10-16 21:02:54.684 | info | serialPort COM6 is open!
maxcul.0 | 2018-10-16 21:02:54.601 | info | using serial device COM6@38400
maxcul.0 | 2018-10-16 21:02:54.530 | info | starting. Version 0.5.3 in C:/Program Files/ioBroker/node_modules/iobroker.maxcul, node: v8.12.0
maxcul.0 | 2018-10-16 21:02:49.629 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:02:44.628 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:02:39.628 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:02:34.627 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:02:29.627 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:02:24.627 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:02:19.626 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:02:14.626 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:02:09.625 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:02:04.624 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:01:59.623 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:01:54.624 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:01:49.624 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:01:44.623 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:01:39.622 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:01:34.621 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:01:29.622 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:01:24.620 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:01:19.620 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:01:14.620 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:01:09.618 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:01:04.618 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:00:59.617 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:00:54.616 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:00:49.615 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:00:44.615 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:00:39.614 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:00:34.614 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:00:29.614 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:00:24.613 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:00:19.612 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:00:14.612 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:00:09.612 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 21:00:04.610 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:59:59.610 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:59:54.609 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:59:49.609 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:59:44.608 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:59:39.608 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:59:34.608 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:59:29.607 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:59:24.607 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:59:19.607 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:59:14.606 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:59:09.606 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:59:04.605 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:58:59.604 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:58:54.604 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:58:49.604 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:58:44.604 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:58:39.604 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:58:34.603 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:58:29.602 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:58:24.603 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:58:19.602 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:58:14.601 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:58:09.600 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:58:04.600 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:57:59.599 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:57:54.599 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:57:49.597 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:57:44.597 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:57:39.596 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:57:34.596 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:57:29.595 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:57:24.594 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:57:19.594 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:57:14.593 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:57:09.592 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:57:04.592 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:56:59.592 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:56:54.591 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:56:49.590 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:56:44.590 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:56:39.589 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:56:34.588 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:56:29.587 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:56:24.586 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:56:19.586 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:56:14.585 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:56:09.584 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:56:04.584 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:55:59.584 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:55:54.583 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:55:49.582 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:55:44.581 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:55:39.580 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:55:34.579 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:55:29.579 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:55:24.578 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:55:19.578 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:55:14.578 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:55:09.577 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:55:04.576 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:54:59.575 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:54:54.575 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:54:49.574 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:54:44.573 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:54:39.572 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:54:34.571 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:54:29.571 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:54:24.570 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:54:19.570 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:54:14.569 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:54:09.568 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:54:04.567 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:53:59.566 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:53:54.566 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:53:49.566 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:53:44.566 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:53:39.565 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:53:34.565 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:53:29.565 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:53:24.565 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:53:19.564 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:53:14.565 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:53:09.563 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:53:04.563 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:52:59.562 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:52:54.562 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:52:49.562 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:52:44.561 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:52:39.560 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:52:34.559 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:52:29.559 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:52:24.559 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:52:19.558 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:52:14.558 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:52:09.556 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:52:04.556 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:51:59.555 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:51:54.554 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:51:49.553 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:51:44.553 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:51:39.553 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:51:34.553 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:51:29.553 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:51:24.552 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:51:19.552 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:51:14.551 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:51:09.552 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:51:04.551 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:50:59.550 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:50:54.549 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:50:49.548 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:50:44.549 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:50:39.549 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:50:34.548 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:50:29.548 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:50:24.549 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:50:19.548 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:50:14.547 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:50:09.546 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:50:04.545 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:49:59.545 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:49:54.544 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:49:49.543 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:49:44.542 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:49:39.542 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:49:34.541 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:49:29.541 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:49:24.540 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:49:19.540 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:49:14.539 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:49:09.538 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:49:04.538 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:48:59.537 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:48:54.536 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:48:49.535 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:48:44.534 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:48:39.533 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:48:34.533 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:48:29.533 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:48:24.534 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:48:19.533 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:48:14.533 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:48:09.533 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:48:04.532 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:47:59.531 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:47:54.530 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:47:49.531 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:47:44.530 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:47:39.529 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:47:34.528 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:47:29.528 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:47:24.528 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:47:19.527 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:47:14.527 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:47:09.526 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:47:04.527 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:46:59.526 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:46:54.526 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:46:49.525 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:46:44.524 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:46:39.525 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:46:34.524 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:46:29.524 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:46:24.523 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:46:19.522 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:46:14.522 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:46:09.521 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:46:04.521 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:45:59.521 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:45:54.520 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:45:49.520 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:45:44.520 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:45:39.519 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:45:34.519 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:45:29.519 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:45:24.519 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:45:19.518 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:45:14.518 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:45:09.518 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:45:04.517 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:44:59.517 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:44:54.517 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:44:49.516 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:44:44.516 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:44:39.515 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:44:34.514 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:44:29.514 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:44:24.514 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:44:19.513 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:44:14.513 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:44:09.512 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:44:04.512 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:43:59.511 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:43:54.511 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:43:49.510 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:43:44.510 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:43:39.509 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:43:34.508 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:43:29.508 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:43:24.508 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:43:19.507 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:43:14.507 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:43:09.507 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:43:04.506 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:42:59.505 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:42:54.505 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:42:49.504 | info | Packet X could not be sent! Error: serial port is not open
maxcul.0 | 2018-10-16 20:42:44.503 | info | Packet X could not be sent! Error: serial port is not open

**Comment by Apollon77** [comment]
Debug loglevel needs to be enabled as instances - expert mode - column log level or such.
