### ISSUE TITLE
Got warn message in the logs

### ISSUE THREAD

**Issue by BigDi** [ioBroker/ioBroker.maxcul#14]
I used a cul flashed Max!Cube and got warn messages every few minutes. I got also no values in the detail view only "&nbsp;". After I clicked in the cell of the value the display change to 0°, 0%, false etc.
The warn message looks like:
unknown device: {"src":"XXXXXX","mode":"0","desiredTemperature":21,"valvePosition":27,"measuredTemperature":20.8,"dstSetting":1,"lanGateway":1,"panel":0,"rfError":0,"batteryLow":0,"untilString":"","r
I can found the device XXXXXX under the max.cul object as a thermostat.
BTW: The devices are not paired.

**Comment by Apollon77** [comment]
Then try to pair them? Do warn disappear then?

**Comment by BigDi** [comment]
I don't know why but after clicking in the value cell and after some time it shows the correct value. But at the moment the window contact is shown as push button and shows no value. Also after clicking in the value cell.

**Comment by Apollon77** [comment]
new issue in new issue please :-)
Ans aldso provide the object definition for the contact with it (Objecta->pencil symbol -> json from "raw" tab)
