### ISSUE TITLE
Wochenprogramme und Pairing zwischen Fensterkontakt und Thermostat

### ISSUE THREAD

**Issue by BigDi** [ioBroker/ioBroker.maxcul#15]
Ich schreibe mal in deutsch, da meines Erachtens die MAX! Komponenten auch nur hier benutzt werden.
Entweder habe ich es noch nicht entdeckt, oder es fehlt noch etwas.
Ich betreibe einen umgeflashten Cube und komme von FHEM.
Dort konnte man schön die Wochenprogramme erstellen und zum Thermostat transferieren, so dass auch ohne Cube diese arbeiten. Zudem fehlt mir die Möglichkeit die Komponenten untereinander zu verheiraten. Auch hier kann ich z.B. den Fensterkontakt mit einem Thermostat verbinden, so dass beim Öffnen des Fenster dies ohne Cube auf die Temperatur fährt, welche unter "Fenster offen" hinterlegt ist.
Mir ist bekannt, dass es für VIS eine Vorlage gibt "Heizungsthermostatsteuerung 2.0 - Script". Aber hier steuert dann iobroker und nicht die Thermonstate selbst - oder?

**Comment by Apollon77** [comment]
Was ist ein "umgeflashter Cube"?

**Comment by Apollon77** [comment]
Der Aktuelle Adapter soll den Cube nicht ersetzen sondern ermöglichen Daten zu lesen bzw "Aktionen" zu steuern.
Daher sind "reine Cube/Setup Features" wie genau das verknüpfen von Kontakten mit Thermostaten oder Wochenprogramme nicht implementiert aktuell, Dafür gibts die App und so ... (nur so als Erklärung)

**Comment by BigDi** [comment]
Der Cube kann zu einem cul bzw. cuno geflashed werden. Hier weitere Infos. 
https://forum.fhem.de/index.php?topic=77590.0
Javascript wäre kein Problem. Nur kenne ich die API von iobroker noch nicht. 
In FHEM ist ja alles implementiert. Eventuell könnte man es von dort übernehmen.

**Comment by danzbox** [comment]
> Der Aktuelle Adapter soll den Cube nicht ersetzen sondern ermöglichen Daten zu lesen bzw "Aktionen" zu steuern.
> Daher sind "reine Cube/Setup Features" wie genau das verknüpfen von Kontakten mit Thermostaten oder Wochenprogramme nicht implementiert aktuell, Dafür gibts die App und so ... (nur so als Erklärung)

In FHEM und Pimatic ist der CUL/MAXCUL Adapter auch dafür da, dass man den Cube nicht mehr braucht, sondern alles über den Cul machen kann (u.a. wegen Cube Alzheimer, Polling etc. wäre es schön ohne Cube auszukommen)
Wenn der iobroker.maxcul Adapter primär nur dafür gedacht ist, passiv mitzulesen, dann wäre mein Vorschlag, dass man das irgendwo in die Adapter Beschreibung packt und die Einschränkungen mal explizit erwähnt. Habe hierzu ein extra Issue eröffnet.
Es ist ja kein Problem, wenn es diese Einschränkungen ggü. FHEM und Pimatic gibt und ich bin auch dankbar für die Arbeit, aber woher soll man das wissen, wenn es nirgends steht?
Für mich ist der Betrieb von MAX! mit Cube z.B. keine Option und ich habe jetzt echt lange gesucht, ob und wie der ioBroker Adapter funktionieren könnte.

**Comment by portyx** [comment]
@danzbox 
da ich auch Probleme hatte mit dem CUL adapter und meinen Cube auch geflashed habe, gab es für mich nur eine Option.

Habe eine FHEM Instanz laufen welche ich ausschließlich für die MAX! Steuerung nutze.
In Verbindung mit dem FHEM Adapter in Iobroker funktioniert das erstaunlich gut.

**Comment by Alexalex89** [comment]
Hallo,
ich möchte mich hier nochmal mit einem Vorschlag einklinken, da ich gerade das gleiche Problem habe.
Ich verstehe, dass du die Kopplung zwischen Thermostat und Fensterkontakt nicht einbauen möchtest. Wäre es vielleicht möglich, dem Thermostat eine Konfiguration (bspw. _windowOpen_) zu spendieren, bei der man via true/false setzen kann, ob die eingestellte _desiredTemperature_ oder die _windowOpenTemperature_ genutzt wird? Denn eine entsprechende Konfiguration mittels NodeRed abzubilden, ist extrem umständlich, da man sich immer die vorher eingestellte _desiredTemperature_ merken muss.
Habe mir gerade kurz den Code angesehen, leider komme ich aber eher aus der Java- und Python-Welt und habe von Node überhaupt keine Ahnung :-(
Viele Grüße und danke für deine Arbeit
Alex

**Comment by Nobby888** [comment]
> Der Aktuelle Adapter soll den Cube nicht ersetzen sondern ermöglichen Daten zu lesen bzw "Aktionen" zu steuern.
> Daher sind "reine Cube/Setup Features" wie genau das verknüpfen von Kontakten mit Thermostaten oder Wochenprogramme nicht implementiert aktuell, Dafür gibts die App und so ... (nur so als Erklärung)

Hallo,
ich dachte auch, dass der Max!CUL-Adapter den Cube ersetzt. Für die Steuerung über den Cube gibt es doch Max!Cube. Gibt es eine Chance, dass die Funktionen in diesen Adapter (oder einen neuen) implementiert werden? Ich möchte mir nicht wirkliche einen Cube kaufen oder eine FHEM-Instanz einrichten.
Keep up the good work, Grüße,
Norbert
