### ISSUE TITLE
Neuer port von pimatic für neue features

### ISSUE THREAD

**Issue by danzbox** [ioBroker/ioBroker.maxcul#21]
Nachdem der Adapter ursprünglich vom Pimatic Adapter stammen soll, rege ich hiermit an, die aktuelle Pimatic Version des CUL Adapters neu zu portieren, um die dort entstandenen Features nutzen zu können. https://github.com/fbeek/pimatic-maxcul

**Comment by Apollon77** [comment]
Leider hat sich der Adapter hier auch weiterentwickelt. Eine Übernahme der Änderungen ist ein Mega merge wo man sehr genau schauen muss was danach nicht mehr tut und welcher change gewinnt und so. 

Wir akzeptieren gern einen PR der dies liefert, ich persönlich habe es zwei mal versucht und aufgegeben. Ich bin aber auch nicht so tief im Thema drin und kann es selbst nicht testen.

**Comment by Apollon77** [comment]
Ps: in dem Zuge bitte auch Update von serialport mit einplanen weil der Adapter aktuell nicht nodejs 10 kompatibel ist.
