### ISSUE TITLE
Fehler aktualisierung

### ISSUE THREAD

**Issue by guergen1** [ioBroker/ioBroker.maxcul#34]
Hallo, 
trotz aktualisiertem Adapter auf 1.1.2 meint iobroker der Adapter wäre nicht aktuell!

**Comment by Apollon77** [comment]
Mehr details? Screenshot? log messages

**Comment by guergen1** [comment]
Sorry... : 
![grafik](https://user-images.githubusercontent.com/34395245/64194283-0285c380-ce7f-11e9-99de-a12e1888230a.png)

![grafik](https://user-images.githubusercontent.com/34395245/64194314-1c270b00-ce7f-11e9-90fa-50a0879eb082.png)

**Comment by Apollon77** [comment]
strange ... lad mal repo neu (Adapter der Button oben links mit den zweiten Pfeilen im Kreis) vor allem weil er es ja anzeigt ...

**Comment by guergen1** [comment]
Ich hab es mittlerweile auf mehrere Arten gemacht:
Auf der Info-Seite, auf der Adapter-Seite, den Adapter gestoppt und bei beiden neu geladen...
Jeweils mit Reboot des Unbuntu‘s...
Nicht dass das daran liegt, da ich ja sämtliche Änderungen über die Tests drin habe?!
Aber irgendwas muss es ja sein...

**Comment by Apollon77** [comment]
Installier einfach vom Github (custom install) drüber

**Comment by guergen1** [comment]
Habe ich grade, bringt auch nix....
Ich meine es ist ja nicht schlimm, dass da steht, dass es ein Update gibt. Wundert mich nur!
Könnte ja auf 1.0.0 downgraden und danach upgraden; nicht dass meine Struktur sich verschiebt wegen den Werten; sollte aber nicht sein!

**Comment by Apollon77** [comment]
also so einen effekt kenn ich nicht .... admin und systeme sollten identisch sein ...

**Comment by guergen1** [comment]
Alles probiert, ausser deinstallieren und neu installieren...!
