### ISSUE TITLE
Config Werte werden nicht übertragen

### ISSUE THREAD

**Issue by Flo-nor** [ioBroker/ioBroker.maxcul#38]
Der MaxCul-Adapter (Iobroker) hat mittlerweile, wie im Changelog beschrieben, Wochenprogramme integriert, womit man die Thermostate direkt mit einem Wochenprogramm versehen kann. Leider gehen meine Einträge im Iobroker nicht an das Thermostat. Anzeige "Bestätigt : False", der Thermostat schaltet auch nicht nach den von mir eingestellten Zeiten. Die Werte BatteryLow, desiredTemperature, measuredTemperature, mode, rferror, rssi und valvePosition überträgt der CUL sauber zum Thermostat und zurück, den Rest nicht. Ich habe die Thermostate gerade im Modus "manuell" laufen und regle das alles über Skripte, die Wochenprogramme direkt am Thermostat zu hinterlegen würde natürlich traffic sparen. Mache ich etwas falsch oder ist das ein Bug? 
![tempsnip](https://user-images.githubusercontent.com/58706900/71689699-01b85c00-2da3-11ea-92a5-784adc2d3646.png)

**Comment by bowao** [comment]
Hi Flo-nor,

die Werte unter 'config' und 'valvaConfig' werden nach manueller Änderung eines Wertes in diesem Block als komplette konfiguration 'config' bzw. 'valveConfig' ans Thermostat gesendet.
Dies funktioniert bei mir einwandfrei und die Thermostate verhalten sich wie gewünscht.
Aber ja du hast recht, die Werte werden im ioBroker nicht auf 'true' gesetzt. Das tut der Funktion zwar keinen Abbruch, aber man könnte das durchaus als Bug ansehen.

Die Werte für das Wochenprogramm unter 'weekProfile' müssen nach manueller Änderung innerhalb eines Tagesblocks zusätzlich manuell über den in diesem Block enthaltenen Datenpunkt 'send_....' zum Thermostat gesendet werden.
Erst nach senden der Daten werden die geänderten Datenpunkte für diesen Tages-Block auf 'true' gesetzt.
Desweitern ist die Umsetzung des Wochenprogramms seitens des Herstellers (eq-3) etwas creepy. 
Anstatt wie gewöhnlich Wertepaare mit einer Uhrzeit mit dem **ab** diesem Zeitpunkt geltenden Sollwert zu bilden, müssen hier Wertepaare mit einer Uhrzeit und **bis** zu diesem Zeitpunkt geltenden Sollwert eingegeben werden.
Das bedeutet, das wenn du Automatisch um 8:00 Uhr vom Nacht-Sollwert (z.B. 17°C) auf den Tag-Sollwert (z.B. 21°C) und um 23:00 Uhr wieder auf den Nachtsollwert schalten möchtest, sieht das Zeitprogramm dann so aus:
```
|Eintrag|  Uhrzeit  |  bis dahin geltender Sollwert |
+-------+-----------+-------------------------------+
|   1   |    8:00   |     17°C                      |
|   2   |   23:00   |     21°C                      |
|   3   |   24:00   |     17°C                      |
+-------+-----------+-------------------------------+
```
Falls das bei dir so nicht funktioniert, dann poste mal bitte dein Thermostat-Typ und das debug-log beim senden des Tages-Blocks.

**Comment by Flo-nor** [comment]
Hi bowao,

zunächst auch nochmal Danke für deine Arbeit und Mühe. MaxCul ist Top, ohne Cloud, genau was ich gesucht habe. 
Zu den Werten unter 'config' und 'valvaConfig' - Stimmt wie beschrieben, Werte werden übertragen, lediglich die Bestätigung fehlt. Läuft aber soweit damit.
Wie von dir beschrieben klappts. auch mit den Wochenprofilen. Auf das senden wäre ich nie gekommen, habe gar nicht so weit runter geschaut. 
Ich bin jetzt alles noch am testen, aber sieht gut aus.
Mal noch eine Frage. Die Limitierung der Befehle, (Not enough credits. Wait for more...)
kommt die vom Stick oder den Thermostaten? Kann man das irgendwie umgehen oder das Limit hochsetzen. Zum testen ist das ein Krampf.

**Comment by bowao** [comment]
Die Credits die du im ioBroker siehst sind vom Stick.
Diese Begrenzung der Sendezeit ist nervig, aber gesetztlich vorgeschrieben.
Eine '**cul firmware to increase send limit**' Version dürfte daher hierzulande natürlich nicht benutzt werden.;)

**Comment by Flo-nor** [comment]
Hi,

ich habe es jetzt 2 Tage am laufen, scheint alles bestens zu funktionieren. Gibt es eine Möglichkeit die Fensterkontakte direkt mit den Thermostaten zu pairen? Ich mache das momentan über Skripte.

**Comment by guergen1** [comment]
Das geht doch „direkt“!

**Comment by Flo-nor** [comment]
Ok, aber wie?

**Comment by bowao** [comment]
Je nach dem welche Thermostate du hast. 
Bei der plus Variante kannst du die Fensterkontakte direkt mit den Thermostaten pairen.
Bei der Standard und der Basic Variante geht das nur indirekt über ein Wandthermostat oder einen cube.
Ich habe die Basic Variante in 8 Räumen mit insgesamt 12 Fensterkontakten. Alle über den ioBroker über scripte.
Funktioniert seit über einem Jahr ohne größere Probleme.

@guergen1:
Hast du mittlerweile herausgefunden wie die Wandthermostate mit den Thermostaten gepairt werden können und trotzdem alle Geräte im ioBroker angezeigt werde?

**Comment by guergen1** [comment]
@bowao angezeigt werden die Daten ja, aber sobald der Thermostat die Regelung übernimmt, vergessen die Thermostate, auf wen sie noch reagieren sollen!
Ich denke, da müsste man sich mal den Cube angucken, der macht ja nichts anderes als der broker

**Comment by Flo-nor** [comment]
Hi bowao,

zunächst mal danke für die Hilfe!! Hast mir einiges an Arbeit erspart. Ich habe den Iobroker mal neu aufgesetzt, dabei kamen neue Modi zum Vorschein. Vorher hatte ich Auto, Manuell und Boost, nun sind noch Man Eco + comfort, Urlaub und Fenster offen dazu gekommen. Mit den (für mich) neuen Modi und den Wochenprofilen lässt sich super arbeiten. Vielen vielen Dank!!!!

**Comment by Flo-nor** [comment]
Hi bowao,

beim einstellen kam doch noch eine Frage auf. Ich habe "window open temperature" auf 5°C, "window open time" auf 5 Min. in der Config eingestellt. Nach meinem Verständnis müssten "mode" und "desired temperature", wenn ich unter mode "manual window" einstelle, nach 5 Minuten zurück auf die vorher eingestellten Werte springen, oder sehe ich das falsch? Bei Boost ist es so.

**Comment by bowao** [comment]
Hi Flo-nor,

die 'window open time' bezieht sich auschließlich auf die im Thermostat selbst vorhandene Fenster offen Erkennung.
Bei abrupt absinkendem Temperaturmesswert, geht das Thermostat davon aus, dass das Fenster geöffnet wurde. Nur dann erscheint auch das Fenster offen sysmbol im Display (zumindestens bei meiner Basic Variante).
Da der Zeitpunkt, wann das Fenster wieder geschlossen wird nicht durch so eine einfache logik automatisch erkannt werden kann, wird zur Rückschaltung einfach eine Zeit vorgegeben.
Wenn man über den 'mode' auf 'Fenster' umschaltet, bleibt das Thermostat auf der eingestellten 'window open temperature' bis der 'mode' wieder geändert wird.
Das macht meines Erachtens auch Sinn, da diese Umschaltung in der Regel von einem Fensterkontakt getriggert wird und daher der genaue Zeitpunkt an dem das Fenster wieder geschlossen wird ja ebenfalls bekannt ist.

**Comment by Flo-nor** [comment]
Hi bowao,

mir ist noch was aufgefallen. Die Thermostate sind alle mit dem week profile eingestellt. Ab und zu kommt es vor dass die Thermostate jedoch mit einer falschen Temperatur fahren. Ich bin nochmal alle meine Skripte durch ob da was schlummert, aber nichts. Vor der Einstellung über week profile habe ich die Thermostate auf Grundeinstellung zurück gesetzt. Dabei erhalten die ja eine Einstellung. Muss man die erst mal löschen? Wenn ja, wie geht das?

**Comment by bowao** [comment]
Die alten Einstellungen zu löschen ist nicht notwendig. 
Beim senden wird automatisch das letzte ausgefüllte Wertepaar (Sollwert und Zeit) auf alle folgenden leeren Einträge übertragen um sicherzustellen das keine Einträge aus alten Zeitprogrammen übrigbleiben.
Zu beachten ist nur, das der letzte eingetragene Sollwert immer bis 24:00 Uhr gelten muss.
Leider hat der Hersteller(eq-3) nicht vorgesehen, das aktuelle Zeitprogramm wieder aus dem Thermostat auslesen zu können, daher lässt sich der korrekte Empfang beim Thermostat nicht prüfen. Bisher hatte ich aber noch keine Probleme mit falsch oder unvollständig übertragenen Zeitprogrammen.
Wird denn immer der gleiche falsche Sollwert angezeigt?
Passiert das immer um die gleiche Zeit?
Sind immer die gleichen Thermostate betroffen?
Steht das Thermostat evtl. in dem Moment auf Manuell? (Polling)
Wie ist das Polling eingestellt? Nach meinen Beobachtungen ist alles unter 10 Minuten Problematisch.
Ansonsten bitte mal das Zeitprogramm eines betroffenen Thermostats und die zugehörigen debug-logs beim senden an das Thermostat hier posten.
