### ISSUE TITLE
Manual Window wird gesetzt, kurz darauf wieder manual Mode

### ISSUE THREAD

**Issue by D3ltorohd** [ioBroker/ioBroker.maxcul#42]
Hallo,
ich weiß nicht wieso das passiert, aber normal denke ich, ist das nicht. Ich setzte per Blockly das Thermostat auf manual window, wenn ich ein Fenster öffne. Dabei wird ja die Window open Temp gesetzt, soweit so gut. Nur nach ein paar Sekunden, steht wieder manual drin ? Das soll doch so bestimmt nicht sein. Ich sehe auch nichts im Log, wer ihn wieder auf manual setzt ? Sollte der manual Window Mode nicht so lange drin stehen, bis ich mein Fenster wieder schließe und den Thermostat auf manual oder auto zurück setzte ?
Grüße

**Comment by bowao** [comment]
Hi D3ltorohd,

solange die Solltemperatur auf der eingestellten Window open Temperatur bleibt ist das normal.
Das Thermostat kann zwar über den Modus "manual window" auf die eingestellte Window open Temperatur geschaltet werden, aber als Antwort bekommst du immer den Modus "manual" vom Thermostat zurück. Ebenfalls bei den Modi "manual eco" und "manual comfort". Deswegen steht bei den modi auch "manual" davor. ;)
Auf dem Thermostat-Display steht auch genau dieser Zustand. Es wird auch nicht das Fenster offen symbol angezeigt. Dies erscheint nur, wenn das Thermostat von sich aus eine Fensteröffnung durch stark abfallende Temperatur erkannt hat. 
Nach schließen des Fensters musst du nur den Modus über dein Skript wieder auf "auto weekly" schalten lassen.
Läuft bei mir seit über einem Jahr mit 8 Thermostaten und 12 Fensterkontakten ohne Probleme.

**Comment by D3ltorohd** [comment]
OK Danke für die Erklärung. Indem Fall ist das soweit iO. Da man ja in ioB kurz manual window sieht, dachte bleibt so lange bis es zurück springt. Das Thermostat bleibt in der Tat auf Off, bzw. auf 4.5° bis ich die Fenster schließe. Hier je nach Raum auf manual + aus einer Variable die zuvor eingestellte Temp. Das läuft jetzt einwandfrei. Indem Fall kann ich das als normal betrachten und es funktionert.

Vielen Dank !!
