### ISSUE TITLE
Serialport wird nicht richtig gepeischert.

### ISSUE THREAD

**Issue by 9Mad-Max5** [ioBroker/ioBroker.maxcul#49]
Ist der Adapter einmal installiert und der Serialport in Zeilenform angegeben kann er nicht geändert werden.
Mein Dropdownmenü bleibt leer und wenn an den anderen werten etwa Scanner was auch immer der bewirkt verstellt wird, kann der Adapter nicht mehr gestartet werden.
Er sagt immer wieder, er kann den cul nicht finden.

**Comment by Apollon77** [comment]
Bitte Screenshot vom Admin zeigen und auch logfile.

**Comment by 9Mad-Max5** [comment]
![2020-07-17 13_26_52-instances - ioBroker und 15 weitere Seiten - Geschäftlich – Microsoft​ Edge](https://user-images.githubusercontent.com/29258083/87782115-361cd280-c832-11ea-9fd0-cf507fbadd15.png)

Logfile ist leider nicht so einfach da ich dann meinen iobroker wieder zurücksetzten, muss.
Drücke ich einmal auf Speichern ist kein Interface mehr gesetzt und der Adapter klappt nicht mehr.
Hier mal noch das JSON aus dem admin selbst:

`{
  "_id": "system.adapter.maxcul.0",
  "common": {
    "name": "maxcul",
    "version": "1.3.0",
    "title": "max! CUL",
    "platform": "javascript/Node.js",
    "mode": "daemon",
    "loglevel": "info",
    "license": "GPL-2.0-only",
    "enabled": true,
    "messagebox": true,
    "materialize": true,
    "icon": "maxcul.png",
    "compact": true,
    "extIcon": "https://raw.githubusercontent.com/ioBroker/ioBroker.maxcul/master/admin/maxcul.png",
    "keywords": [
      "cul",
      "MAX!",
      "868",
      "busware"
    ],
    "readme": "https://github.com/ioBroker/ioBroker.maxcul/blob/master/README.md",
    "type": "iot-systems",
    "authors": [
      {
        "name": "bluefox",
        "email": "dogafox@gmail.com"
      }
    ],
    "installedFrom": "iobroker.maxcul@1.3.0",
    "installedVersion": "1.3.0",
    "host": "iobroker"
  },
  "native": {
    "serialport": null,
    "baudrate": "38400",
    "baseAddress": "000000",
    "scanner": "0"
  }
}`

**Comment by Apollon77** [comment]
und welche Optionen stehen in der selection drin?

Ohne logfile ist aber sehr blöd, wie soll ich da wissen was ggf ist?

**Comment by 9Mad-Max5** [comment]
Keine es ist nichts auszuklappen.
Es bleibt einfach leer oder als gebe es kein Dropdown.

**Comment by 9Mad-Max5** [comment]
Ich kann leider nicht reopennen.

Sobald der Adapter gestartet wird, kann ich das Device nicht mehr auswählen.
Also sieht es dann wieder wie zuvor aus.

**Comment by Apollon77** [comment]
Sicher das es nicht an dem anderen issue mit serialport liegt? Bitte das zuerst fixen, dann neu schauen
