### ISSUE TITLE
checkTimeIntervalFired führt zum Adapter Neustart

### ISSUE THREAD

**Issue by AlterMann64** [ioBroker/ioBroker.maxcul#52]
Mit der CUL FW Version: V 1.67 CUL868 ......auf Busware CUL oder auf geflashtem MaxCube gleicher Fehler ca. jede Stunde.

maxcul.0 | 2020-07-25 08:13:40.034 | info | (9623) Terminated (NO_ERROR): Without reason
maxcul.0 | 2020-07-25 08:13:40.032 | info | (9623) terminating
maxcul.0 | 2020-07-25 08:13:40.014 | error | (9623) unhandled promise rejection: undefined
Unhandled | 2020-07-25 08:13:40.013 | error | promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
maxcul.0 | 2020-07-25 08:13:27.971 | info | (9623) checkTimeIntervalFired

Läuft auf Raspi 4 , Adapter mit  reboot mehrfach neu installiert....keine Änderung

Mathias

**Comment by bowao** [comment]
Hast du die Version aus dem Github Repository installiert?
Falls nicht bitte mal testen, sollte dort gefixt sein.

**Comment by guergen1** [comment]
Bei mir ist der Fehler nach der Installation aus github weg!

**Comment by AlterMann64** [comment]
werde es testen

Danke.. meld mich

**Comment by AlterMann64** [comment]
Danke Euch das war die Lösung
