### ISSUE TITLE
Adapter won't start after Update to Node.js 18.11.0 

### ISSUE THREAD

**Issue by 6RomN6** [ioBroker/ioBroker.maxcul#62]
After the Update the Adapter not start anymore...

I don't know if it a problem of my installation or is it a general problem?

Logs:
`<html>
<body>

maxcul.0 | 2023-04-11 14:54:49.206 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
maxcul.0 | 2023-04-11 14:54:49.206 | info | terminating
maxcul.0 | 2023-04-11 14:54:49.205 | error | Exception-Code: ERR_DLOPEN_FAILED: Module did not self-register: '/opt/iobroker/node_modules/@serialport/bindings/build/Release/bindings.node'.
maxcul.0 | 2023-04-11 14:54:49.204 | error | Error: Module did not self-register: '/opt/iobroker/node_modules/@serialport/bindings/build/Release/bindings.node'. at Module._extensions..node (node:internal/modules/cjs/loader:1243:18) at Module.load (node:internal/modules/cjs/loader:1037:32) at Module._load (node:internal/modules/cjs/loader:878:12) at Module.require (node:internal/modules/cjs/loader:1061:19) at require (node:internal/modules/cjs/helpers:103:18) at bindings (/opt/iobroker/node_modules/bindings/bindings.js:112:48) at Object.<anonymous> (/opt/iobroker/node_modules/@serialport/bindings/lib/linux.js:2:36) at Module._compile (node:internal/modules/cjs/loader:1159:14) at Module._extensions..js (node:internal/modules/cjs/loader:1213:10) at Module.load (node:internal/modules/cjs/loader:1037:32) at Module._load (node:internal/modules/cjs/loader:878:12) at Module.require (node:internal/modules/cjs/loader:1061:19) at require (node:internal/modules/cjs/helpers:103:18) at Object.<anonymous> (/opt/iobroker/node_modules/@serialport/bindings/lib/index.js:14:22) at Module._compile (node:internal/modules/cjs/loader:1159:14) at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
maxcul.0 | 2023-04-11 14:54:49.204 | error | uncaught exception: Module did not self-register: '/opt/iobroker/node_modules/@serialport/bindings/build/Release/bindings.node'.
maxcul.0 | 2023-04-11 14:54:49.079 | info | starting. Version 1.3.1 in /opt/iobroker/node_modules/iobroker.maxcul, node: v18.11.0, js-controller: 4.0.24
maxcul.0 | 2023-04-11 12:54:17.876 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason

</body>
</html>`

**Comment by Apollon77** [comment]
siehe https://forum.iobroker.net/topic/44566/how-to-node-js-iobroker-richtig-updaten-2021-22-edition/2 unter "Sonderfälle"
